dist: trusty
language: ruby
cache: bundler
before_install:
   bundle -v
script: env COVERAGE=yes bundle exec rake test
matrix:
  fast_finish: true
  include:
  - env: PUPPET_GEM_VERSION="~> 6.0"
    rvm: 2.5.1
  - env: PUPPET_GEM_VERSION="~> 5.0"
    rvm: 2.4.4

